<a href="https://colab.research.google.com/github/AditMeh/deep-learning/blob/main/ResNets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import keras 
import numpy as np
import tensorflow as tf
import tensorflow.keras.backend as K
import matplotlib.pyplot as plt

(train_images, train_labels), (test_images, test_labels) = keras.datasets.cifar10.load_data()

print(train_images.shape)
print(train_labels.shape)
print(test_images.shape)
print(test_labels.shape)

170500096/170498071 [==============================] - 11s 0us/step
(50000, 32, 32, 3)
(50000, 1)
(10000, 32, 32, 3)
(10000, 1)


In [ ]:
from keras.utils import to_categorical
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

def process_images(image, label):
    label =  tf.squeeze(tf.one_hot(label, depth  = 10))
    return image, label

val_train_split = round(0.80*len(train_images))

val_images, val_labels = train_images[val_train_split:], train_labels[val_train_split:]

train_ds = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
test_ds = tf.data.Dataset.from_tensor_slices((test_images, test_labels))
validation_ds = tf.data.Dataset.from_tensor_slices((val_images, val_labels))

train_dataset = (train_ds
                  .map(process_images)
                  .shuffle(buffer_size= 10)
                  .batch(batch_size=128, drop_remainder=True))
test_dataset = (test_ds
                  .shuffle(buffer_size=10)
                  .map(process_images)
                  .batch(batch_size=128, drop_remainder=True))
val_dataset = (validation_ds
                  .map(process_images)
                  .shuffle(buffer_size=10)
                  .batch(batch_size=32, drop_remainder=True))


In [ ]:
class ResidualBlock(keras.layers.Layer):
    def __init__(self, filters, pad):
        super().__init__()
        # self.conv1 = keras.layers.Conv2D(filters, kernel_size= (3, 3), 
        #                                  strides= 1,
        #                                  padding = "same",
        #                                  activation = "relu",
        #                                  data_format="channels_last",
        #                                  kernel_initializer='GlorotNormal')
            
        # self.conv2 = keras.layers.Conv2D(filters, kernel_size = (3,3),
        #                                  strides = 1,
        #                                  padding = "valid",
        #                                  activation = None,
        #                                  data_format = "channels_last",
        #                                  kernel_initializer = "GlorotNormal")
            
        #self.batchnorm1 = keras.layers.BatchNormalization()
        #self.batchnorm2 = keras.layers.BatchNormalization()

        #self.zero_padding = keras.layers.ZeroPadding2D(padding = (pad, pad), data_format= "channels_last")

        def call(self, X):            
            conv1 = self.conv1(X)
            bn1 = self.batchnorm1(conv1)
            conv2 = self.conv2(bn1)
            bn2 = self.batchnorm2(conv2)

            return keras.activations.activation.relu(bn2 + self.zero_padding(X))

In [ ]:
model = ResidualBlock(32, 16)
thing = np.ones((1, 32, 32, 3), dtype = np.float32)

print(model.call(thing))
#print(model.conv2(thing).shape)



[[[[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  ...

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]
   ...
   [1. 1. 1.]
   [1. 1. 1.]
   [1. 1. 1.]]]]
